### ISSUE TITLE
Container not starting

### ISSUE THREAD

**Issue by kinafu** [padhi-homelab/docker_tang#1]
Using the tang image published on dockerhub (image ID `017a42d3b036`) I could not get tang to a succesful startup.

Maybe it's due to using `podman` instead of `docker`?
In case you, @SaswatPadhi, are successfully using `podman`, too, the issue might be caused by something different.

`podman run -it --rm padhihomelab/tang`

returns:
```
[2020-11-20 21:17:38] /usr/local/bin/docker-entrypoint: No files found in /etc/docker-entrypoint.d, skipping configuration.
[2020-11-20 21:17:38] /usr/local/bin/docker-entrypoint: Creating new user 'user' with UID = 12345 in group user (23456) ...
[2020-11-20 21:17:38] /usr/local/bin/docker-entrypoint: User 'user' created successfully.
[2020-11-20 21:17:38] /usr/local/bin/docker-entrypoint: Ready for start up.
mkdir: can't create directory 'db/tang': Permission denied
```

**Comment by SaswatPadhi** [comment]
Hi @kinafu,

Thanks for reporting this. Sorry about that!
I noticed this issue a while ago and have already fixed it in the base image (`alpine-base`, see [this commit](https://github.com/padhi-homelab/docker_alpine-base/commit/7bfdd840333f052398c10220c7d62af3310dd30b)), but forgot to rebuilt the `tang` image.

Let me do that right away.

**Comment by SaswatPadhi** [comment]
I just rebuilt the image and tested that `padhhomelab/tang:latest` works as expected on my machine.

I haven't tried with podman though. Please feel free to reopen this issue if you still encounter this bug.

Thanks! :)

**Comment by SaswatPadhi** [comment]
@kinafu: You also need to specify a volume mount:

```
docker run -v $(pwd)/data/tang/db:/home/user/db:rw ...
```

**Comment by SaswatPadhi** [comment]
@kinafu: You also need to specify a volume mount:

```
docker run -v $(pwd)/data/tang/db:/home/user/db ...
```

I am not exactly sure about the `podman` cmdline flags for volumes.

**Comment by SaswatPadhi** [comment]
Sorry for all the noise. I just realized I had misinterpreted this issue and was referring to a different issue.

I just fixed the root cause for the behavior that you're seeing.

**Comment by SaswatPadhi** [comment]
This time I'm certain I fixed the actual root cause for this behavior. @kinafu, please check at your end with `podman` and feel free to open it if you still observe this behavior.

Thanks! :)

**Comment by kinafu** [comment]
Thanks a lot, that fixes it for me! :grinning:
