### ISSUE TITLE
Data should not (also) expose cache dir

### ISSUE THREAD

**Issue by rugk** [padhi-homelab/docker_tang#3]
https://github.com/padhi-homelab/docker_tang/blob/bb3079b3472d957410b7ab48728eb714f7f13f40/Dockerfile#L81

…defines a volume for _both_ the cache dir and the keys DB. IMHO that is not a good way, because usually temp files should only be stored temporarily (in a `tmpfs`) and actually also do not need to be exposed.
IMHO, it would be good to keep this "temp stuff" one anyway would not want to modify inside the container and not expose it. Also one should not run `tang-update` from outside of this container IMHO as one does not know what the state inside the container is (it should work from the outside – even if you upgrade it and paths are changed etc.)

## Suggested solution

At least two volumes for temp/cache files and one for the keys DB. And the temp/cache volume should be stored on a tmpfs, also for security reasons, so to not spread the key material and save it to different places.
See https://github.com/latchset/tang/issues/24 and https://github.com/latchset/tang/issues/23

Or just don't expose the cache dir at al. :wink:

**Comment by SaswatPadhi** [comment]
Great point! Thanks, @rugk! :)

I'll go with the latter solution -- not expose the cache at all.

**Comment by SaswatPadhi** [comment]
Okay I think I've fixed this now :) Had some issues with the CI, but it seems happy now.
