### ISSUE TITLE
No cache regeneration mechanism?

### ISSUE THREAD

**Issue by rugk** [padhi-homelab/docker_tang#4]
It seems you only generate the cache files once at startup:

https://github.com/padhi-homelab/docker_tang/blob/bb3079b3472d957410b7ab48728eb714f7f13f40/init-tangd.sh#L6

This means if the key files are changed on disk at runtime, this change is not reflected in the cache and thus tang will still use the old keys. If you bind that keys DB volume as an external dir, as https://github.com/padhi-homelab/docker_tang/pull/2 e.g. suggests, you end up having both dirs exposed at runtime, but one is managed inside of the container. (see also https://github.com/padhi-homelab/docker_tang/issues/3)
AFAIK upstream tang solves this with a systemd unit, which is of course not possible here.

See https://github.com/latchset/tang/issues/24 and https://github.com/latchset/tang/issues/23. So as this cache thing is anyway not a good idea, I think you should IMHO encapsulate that cache thing.
Or you do not expose the cache dir (https://github.com/padhi-homelab/docker_tang/issues/3) and then maybe add a note in the Readme that one needs to restart the container if the keys are regenerated/changed.
(Or add some command to regenerate/[rotate](https://github.com/latchset/tang#key-rotation) keys or whatever)

**Comment by SaswatPadhi** [comment]
Thanks a lot for all the details, @rugk.

I read the discussions carefully, and considered the solution you mentioned (hiding cache and adding some commands / notes about key rotation), but the cleanest solution seemed to be applying the RHEL-8 patch mentioned in latchset/tang#24.

There were a few build minor build issues after patching, so I had to add a second patch: https://github.com/padhi-homelab/docker_tang/blob/main/0002-fix-build-issues-after-RHEL-8-patch.patch

**Comment by rugk** [comment]
Awesome though! Let's hope this get's upstream :smiley:  (if you wanna do a PR, feel free to try :upside_down_face:)
